---
 - name: checking for postgres container
   shell: "dokku postgresql:list"
   register: postgres_check

 - name: creating postgres container
   shell: "dokku postgresql:create objective8_postgres"
   when: postgres_check.stdout.find('objective8_postgres') == -1

 - name: checking for objective8
   shell: "dokku apps"
   register: objective8_check

 - name: creating objective8 app
   shell: "dokku apps:create objective8"
   when: objective8_check.stdout.find('objective8') == -1

