---
 - name: create objective8 database
   postgresql_db: name=objective8 login_user=postgres
   sudo_user: postgres

 - name: add objective8 role
   #TODO - password management
   postgresql_user: name=objective8 login_user=postgres password={{ DB_PASSWORD }} db=objective8
   sudo_user: postgres

 - name: give objective8 user CREATE on database
   postgresql_privs: role=objective8 database=objective8 state=present privs=CREATE type=database
   sudo_user: postgres

 - name: create .pgpass file
   lineinfile: dest=/usr/local/objective8/.pgpass state=present create=yes line="localhost:5432:objective8:objective8:{{ DB_PASSWORD }}" mode=0600

 - name: copy postgres hba config file to /etc/postgresql
   copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
         owner=postgres group=postgres mode=0700

 - name: copy postgres config file to /etc/postgresql
   copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
         owner=postgres group=postgres mode=0700