---
 - name: install git
   apt: name=git state=present

 - name: install node.js
   apt: name=nodejs state=present

 - name: symlink node->nodejs
   file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

 - name: install npm
   apt: name=npm state=present

 - name: Node.js | Install packages
   npm: name={{item}} global=yes
   with_items:
     - grunt-cli

 - name: install docker.io
   apt: name="docker.io" state=present

 - name: install firefox
   apt: name=firefox state=present

 - name: install xvfb
   apt: name=xvfb state=present
