---
 - name: update apt
   command: sudo apt-get update

 - name: install git
   apt: name=git state=present

 - name: install node.js
   apt: name=nodejs state=present

 - name: install npm
   apt: name=npm state=present

