---
 - name: update apt
   command: sudo apt-get update

 - name: install git
   apt: name=git state=present

 - name: install node.js
   apt: name=nodejs state=present

 - name: symlink node->nodejs
   file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

 - name: install npm
   apt: name=npm state=present

 - name: install docker.io
   apt: name="docker.io" state=present
